program SCIT_2001;

uses
  Forms,
  Principal in 'Principal.pas' {FrmMain},
  UntCadCli in 'UntCadCli.pas' {FrmCadCli},
  UntDataModulo in 'UntDataModulo.pas' {DmPrincipal: TDataModule},
  UntPesqCadCli in 'UntPesqCadCli.pas' {FrmPesqCadCli},
  UntCadProdFra in 'UntCadProdFra.pas' {FrmCadProdFra},
  UntPesqCadProdBoi in 'UntPesqCadProdBoi.pas' {FrmPesqCadProdBoi},
  UntSplashForm in 'UntSplashForm.pas' {FrmSplashForm},
  UntPedidoAvicola in 'UntPedidoAvicola.pas' {FrmPedidoAvicola},
  UntConf_Itens_Fra in 'UntConf_Itens_Fra.pas' {FrmConf_Itens_Fra},
  UntConf_Venda_Fra in 'UntConf_Venda_Fra.pas' {FrmConf_Venda_Fra},
  UntCalendario in 'UntCalendario.pas' {FrmCalendario},
  UntReorganiza in 'UntReorganiza.pas' {FrmReorganiza},
  untSobre in 'untSobre.pas' {frmSobre},
  UntBackupRestore in 'UntBackupRestore.pas' {FrmBackupRestore},
  UntAlteraPedidoAvicola in 'UntAlteraPedidoAvicola.pas' {FrmAlteraPedidoAvicola},
  UntAlteraItensFra in 'UntAlteraItensFra.pas' {FrmAlteraItensFra},
  UntAlteraPedidoVendaFra in 'UntAlteraPedidoVendaFra.pas' {FrmAlteraPedidoVendaFra},
  UntBaixaCancelamentoContasReceberAvicola in 'UntBaixaCancelamentoContasReceberAvicola.pas' {FrmBaixaCancelamentoContasReceberAvicola},
  UntConfirmaBaixaContasReceberAvicola in 'UntConfirmaBaixaContasReceberAvicola.pas' {FrmConfirmaBaixaContasReceberAvicola},
  UntDevolucaoAvicola in 'UntDevolucaoAvicola.pas' {FrmDevolucaoAvicola},
  UntConf_Itens_DevFra in 'UntConf_Itens_DevFra.pas' {FrmConf_Itens_DevFra},
  UntAlteraDevolucaoAvicola in 'UntAlteraDevolucaoAvicola.pas' {FrmAlteraDevolucaoAvicola},
  UntConfirmaDevolucaoAvicola in 'UntConfirmaDevolucaoAvicola.pas' {FrmConfirmaDevolucaoAvicola},
  UntListaProdutosAvicola in 'UntListaProdutosAvicola.pas' {FrmListaProdutosAvicola},
  UntQrListaProdutosAvicola in 'UntQrListaProdutosAvicola.pas' {FrmQrListaProdutosAvicola},
  UntListaClientesResumido in 'UntListaClientesResumido.pas' {FrmListaClientesResumido},
  UntQrListaClientesResumido in 'UntQrListaClientesResumido.pas' {FrmQrListaClientesResumido},
  UntRelatorioSinteticoContasReceberAvicola in 'UntRelatorioSinteticoContasReceberAvicola.pas' {FrmRelatorioSinteticoContasReceberAvicola},
  UntQrRelatorioSinteticoContasReceberAvicola in 'UntQrRelatorioSinteticoContasReceberAvicola.pas' {FrmQrRelatorioSinteticoContasReceberAvicola},
  UntRelatorioPedidoPeriodoAvicola in 'UntRelatorioPedidoPeriodoAvicola.pas' {FrmRelatorioPedidoPeriodoAvicola},
  UntQrRelatorioPedidoPeriodoAvicola in 'UntQrRelatorioPedidoPeriodoAvicola.pas' {FrmQrRelatorioPedidoPeriodoAvicola},
  UntRelatorioEstatisticaPedidosAvicola in 'UntRelatorioEstatisticaPedidosAvicola.pas' {FrmRelatorioEstatiticaPedidosAvicola},
  UntQrRelatorioEstatisticaPedidosAvicola in 'UntQrRelatorioEstatisticaPedidosAvicola.pas' {FrmQrRelatorioEstatisticaPedidosAvicola},
  UntRelatorioAnaliticoContasRecerberAvicola in 'UntRelatorioAnaliticoContasRecerberAvicola.pas' {FrmRelatorioAnaliticoContasRecerberAvicola},
  UntRelatorioSintesePedidosAvicola in 'UntRelatorioSintesePedidosAvicola.pas' {FrmRelatorioSintesePedidosAvicola},
  UntQRRelatorioSintesePedidosAvicola in 'UntQRRelatorioSintesePedidosAvicola.pas' {FrmQRRelatorioSintesePedidosAvicola},
  UntCriaTabelas in 'UntCriaTabelas.pas' {FrmCriaTabela},
  requisicao in 'requisicao.pas' {FrmRequisicao},
  UntListaClientesCompleto in 'UntListaClientesCompleto.pas' {FrmListaClientesCompleto},
  UntQrListaClientesCompleto in 'UntQrListaClientesCompleto.pas' {FrmQrListaClientesCompleto},
  UntListaGastosVeiculos in 'UntListaGastosVeiculos.pas' {FrmListaGastosVeiculos},
  UntQrListaGastosVeiculos in 'UntQrListaGastosVeiculos.pas' {FrmQRListaGastosVeiculos},
  UntExcluiAlteraRequisicoes in 'UntExcluiAlteraRequisicoes.pas' {FrmExcluiAlteraRequisicoes},
  UntRelatorioSinteseDevolucaoAvicola in 'UntRelatorioSinteseDevolucaoAvicola.pas' {FrmRelatorioSinteseDevolucaoAvicola},
  UntQRRelatorioDevolucoesPeriodoAvicola in 'UntQRRelatorioDevolucoesPeriodoAvicola.pas' {FrmQRRelatorioDevolucoesPeriodoAvicola},
  UntRelatorioDevolucoesPeriodoAvicola in 'UntRelatorioDevolucoesPeriodoAvicola.pas' {FrmRelatorioDevolucoesPeriodoAvicola},
  TcCombobox in '..\The Club Instructions\TcCombobox.pas',
  UntQRRelatorioSinteseDevolucaoAvicola in 'UntQRRelatorioSinteseDevolucaoAvicola.pas' {FrmQRRelatorioSinteseDevolucaoAvicola},
  UntCadProdBoi in 'UntCadProdBoi.pas' {FrmCadProdBoi},
  UntPesqCadProdFra in 'UntPesqCadProdFra.pas' {FrmPesqCadProdFra},
  UntListaProdutosBoi in 'UntListaProdutosBoi.pas' {FrmListaProdutosBoi},
  UntQrListaProdutosBoi in 'UntQrListaProdutosBoi.pas' {FrmQrListaProdutosBoi},
  UntPedidoAcougue in 'UntPedidoAcougue.pas' {FrmPedidoAcougue},
  UntConf_Itens_Boi in 'UntConf_Itens_Boi.pas' {FrmConf_Itens_Boi},
  UntConf_Venda_Boi in 'UntConf_Venda_Boi.pas' {FrmConf_Venda_Boi},
  UntAlteraPedidoAcougue in 'UntAlteraPedidoAcougue.pas' {FrmAlteraPedidoAcougue},
  UntAlteraItensBoi in 'UntAlteraItensBoi.pas' {FrmAlteraItensBoi},
  UntAlteraPedidoVendaBoi in 'UntAlteraPedidoVendaBoi.pas' {FrmAlteraPedidoVendaBoi},
  UntDevolucaoAcougue in 'UntDevolucaoAcougue.pas' {FrmDevolucaoAcougue},
  UntConfirmaDevolucaoAcougue in 'UntConfirmaDevolucaoAcougue.pas' {FrmConfirmaDevolucaoAcougue},
  UntConf_Itens_DevBoi in 'UntConf_Itens_DevBoi.pas' {FrmConf_Itens_DevBoi},
  UntAlteraDevolucaoAcougue in 'UntAlteraDevolucaoAcougue.pas' {FrmAlteraDevolucaoAcougue},
  UntBaixaCancelamentoContasReceberAcougue in 'UntBaixaCancelamentoContasReceberAcougue.pas' {FrmBaixaCancelamentoContasReceberAcougue},
  UntConfirmaBaixaContasReceberAcougue in 'UntConfirmaBaixaContasReceberAcougue.pas' {FrmConfirmaBaixaContasReceberAcougue},
  UntRelatorioPedidoPeriodoAcougue in 'UntRelatorioPedidoPeriodoAcougue.pas' {FrmRelatorioPedidoPeriodoAcougue},
  UntQrRelatorioPedidoPeriodoAcougue in 'UntQrRelatorioPedidoPeriodoAcougue.pas' {FrmQrRelatorioPedidoPeriodoAcougue},
  UntRelatorioEstatisticaPedidosAcougue in 'UntRelatorioEstatisticaPedidosAcougue.pas' {FrmRelatorioEstatiticaPedidosAcougue},
  UntFechamentoPedidosPeriodoAvicola in 'UntFechamentoPedidosPeriodoAvicola.pas' {FrmFechamentoPedidosPeriodoAvicola},
  UntFechamentoPedidosPeriodoAcougue in 'UntFechamentoPedidosPeriodoAcougue.pas' {FrmFechamentoPedidosPeriodoAcougue},
  UntCadPrestadora in 'UntCadPrestadora.pas' {FrmCadPrestadora},
  UntCadVeiculos in 'UntCadVeiculos.pas' {FrmCadVeiculos},
  UntIncluiItensboi in 'UntIncluiItensboi.pas' {FrmInclui_Itens_Boi},
  UntIncluiItensFra in 'UntIncluiItensFra.pas' {FrmInclui_Itens_Fra},
  UntAlteraDevolucaoFra in 'UntAlteraDevolucaoFra.pas' {FrmAlteraDevolucaoFra},
  UntAlteraItensDevFra in 'UntAlteraItensDevFra.pas' {FrmAlteraItensDevFra},
  UntIncluiItensDevFra in 'UntIncluiItensDevFra.pas' {FrmInclui_Itens_DevFra},
  UntAlteraDevolucaoBoi in 'UntAlteraDevolucaoBoi.pas' {FrmAlteraDevolucaoBoi},
  UntAlteraItensDevBoi in 'UntAlteraItensDevBoi.pas' {FrmAlteraItensDevBoi},
  UntIncluiItensDevBoi in 'UntIncluiItensDevBoi.pas' {FrmInclui_Itens_DevBoi},
  UntRelatorioDevolucoesPeriodoAcougue in 'UntRelatorioDevolucoesPeriodoAcougue.pas' {FrmRelatorioDevolucoesPeriodoAcougue},
  UntQRRelatorioDevolucoesPeriodoAcougue in 'UntQRRelatorioDevolucoesPeriodoAcougue.pas' {FrmQRRelatorioDevolucoesPeriodoAcougue},
  UntQrRelatorioEstatisticaPedidosAcougue in 'UntQrRelatorioEstatisticaPedidosAcougue.pas' {FrmQrRelatorioEstatisticaPedidosAcougue},
  UntRelatorioSintesePedidosAcougue in 'UntRelatorioSintesePedidosAcougue.pas' {FrmRelatorioSintesePedidosAcougue},
  UntQRRelatorioSintesePedidosAcougue in 'UntQRRelatorioSintesePedidosAcougue.pas' {FrmQRRelatorioSintesePedidosAcougue},
  UntRelatorioSinteticoContasReceberAcougue in 'UntRelatorioSinteticoContasReceberAcougue.pas' {FrmRelatorioSinteticoContasReceberAcougue},
  UntQrRelatorioSinteticoContasReceberAcougue in 'UntQrRelatorioSinteticoContasReceberAcougue.pas' {FrmQrRelatorioSinteticoContasReceberAcougue},
  UntQrListaContasReceberAnalitico in 'UntQrListaContasReceberAnalitico.pas' {FrmQrListaContasReceberAnalitico};

{$R *.RES}

begin
  Application.Initialize;
  FrmSplashForm := TFrmSplashForm.Create(Application);
  FrmSplashForm.Update;
  FrmSplashForm.Show;
  Application.Title := 'SCIT_2001';
  Application.CreateForm(TFrmMain, FrmMain);
  Application.CreateForm(TDmPrincipal, DmPrincipal);
  FrmSplashForm.Close;
  Application.Run;
end.
